### ISSUE TITLE
Invalid Domain?

### ISSUE THREAD

**Issue by davmaz** [avelex/passwordme#1]
Great program! If I use https://github.com I get invalid domain. I can't figure out what is considered a "valid domain" though - any hints?

**Comment by avelex** [comment]
Hi @davmaz! Nice to hear that you tried the app, thank you!
If you  write ```github.com``` , it'll work. 
I think it makes sense to improve the function of determining the domain from the url

**Comment by avelex** [comment]
Are you using the latest version (v0.1.2)? 

Yes you can use your github password as a master password with no problem. 

And you can also use whatever password is easy to remember, like alex123 :)

**Comment by avelex** [comment]
Here, at the bottom left
![image](https://github.com/avelex/passwordme/assets/37179175/3f727a96-e80f-4170-ab16-008d462090c9)

**Comment by avelex** [comment]
Yep, Dave, there is a bug, the field ```domain``` doesn't refresh when you paste ```https://github.com ``` and then remove ```https://```.  

When you paste the correct domain ```github.com``` it works

As for the version, you should run the ```make build``` command, and then the version from git will pull up and be the latest version. 

Before ```make build```, please make ```go install fyne.io/fyne/v2/cmd/fyne@latest```

**Comment by avelex** [comment]
Could you please try this installing steps? 
https://github.com/avelex/passwordme#installing

**Comment by avelex** [comment]
Hi @davmaz! Could you please make  ```git tag``` ? And paste result here

**Comment by avelex** [comment]
Hi @davmaz! I am published v0.1.3 of app. Can u please check your first problem with domain? If it's okay, I will closed this issue. 

And if you need to solve your tag problem, I can open new issue
